server:
  port: 8889

spring:
  datasource:
    username: root
    password: 710714
    url: jdbc:mysql://localhost:3306/chh?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:recom_crawl/*Mapper.xml
  type-aliases-package: com.sohu.springbootdemo.Model

#showSql
logging:
  level:
    com:
      sohu:
        springbootdemo:
          Dao : debug